# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08c1e95700c1a9b6a634245dc6b82f57482f52d4f336fe06f62709b31a5765893ea4d3067f9adac960b5c41adb6dd785389cc1d7b11656c25c5c87ba38143da

test:
  secret_key_base: 52a39b04be98385bc1e7f806672a98edaae765d4c51068e5fb67632f1eae743ed009a1462366ec6aa3301cf980d6f33af133bfb3dfe6b4a3dd5dd4ed026f7cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
